version: '3.8'

services:
  secure.identityserver:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - ASPNETCORE_HTTPS_PORTS=81
    ports:
      - "5000:80"
      - "5001:81"
    restart: always
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    networks:
      - service-network

  securemicroservice.movies.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - ASPNETCORE_HTTPS_PORTS=81
      - IdentityServerUrl=https://host.docker.internal:5001/
    restart: always
    ports:
      - "5005:80"
      - "5006:81"
    depends_on:
      - secure.identityserver
    command: apt-get update -y && apt-get install -y iputils-ping
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    networks:
      - service-network

networks:
  service-network: